postgresql:
    image: postgres
    container_name: 112_queue_postgres
    restart: always
    labels: 
        - "112_queue"
    expose:
        - "5432"
    environment:
        - POSTGRES_PASSWORD=supersecret
        - POSTGRES_DB=queue
        - POSTGRES_USER=queue

nodeapp:
    build: app 
    container_name: 112_queue_nodeapp
    restart: always
    links:
        - postgresql
    labels:
        - "112_queue"
    expose:
        - "3000"
    ports: 
        - "3000:3000"



